import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
// import Test from '../components/Test'
import styles from '../styles/Home.module.css'

const Test = dynamic(() => import('../components/Test'), {
  suspense: true,
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Test />
    </div>
  )
}

export default Home
